/* Understand the performance of each product. Design an SQL query that:
        1. Computes the total revenue generated by each product (`v2ProductName`).
        2. Determines the total quantity sold for each product.
        3. Calculates the total refund amount for each product.
    - Rank products based on their net revenue (total revenue minus refunds) in a descending order. Flag any product with a refund amount surpassing 10% of its total revenue.
*/

SELECT
    v2ProductName,
    SUM(productRevenue) AS totalRevenue,
    SUM(productQuantity) AS totalQuantitySold,
    SUM(productRefundAmount) AS totalRefundAmount,
    SUM(productRevenue) - SUM(productRefundAmount) AS netRevenue,
    -- Flag any product with a refund amount surpassing 10% of its total revenue.
    CASE
        WHEN SUM(productRefundAmount) > 0.1 * SUM(productRevenue) THEN 'Flagged'
        ELSE 'Not Flagged'
    END AS refundFlag
FROM 
    "DWH".ecommerce_session ecommerce
GROUP BY 
    v2ProductName
ORDER BY 
    netRevenue DESC;